### ISSUE TITLE
Parent group is not saved when pasting objects

### ISSUE THREAD

**Issue by RueOfficial** [Alphalaneous/Auto-Build-Helper#2]
Kind of self explanatory, when pasting objects, if there is a object, with lets say... group 10 with the flag parent,when pasting it, it will default to a regular group instead of being a parent, this bugs custom objects that use group parent for stuff

how to repro:
1) create of copy a set of triggers that use a group parent
2) add them to your custom objects
3) enable auto build helper
4) paste the custom object you previously saved on step # 2
5) check for the object that is supposed to have the group parent

**Comment by Alphalaneous** [comment]
This is unfortunately a vanilla GD bug and not a bug with the mod. Copy Paste/Custom Objects don’t properly save group parents.

**Comment by RueOfficial** [comment]
oh damn i didnt knew, rip :c

however, vanilla gd does properly save group parent when adding them to custom object, it doesn't save it properly when doing a regular copy/paste. i guess it still cannot be fixed since probably the mod uses the function of copy/paste that robtop made, i actually really dont know im just talking out of my ass xD

**Comment by Alphalaneous** [comment]
Can confirm that if vanilla does save group parent for custom objects, that it does not even with Auto Build Helper disabled, so it is unrelated to this mod anyways
